export const data = [
  {
    FirstName: "Jitender",
    Date: new Date("01/09/2015"),
    Examination: "Français",
    Note: "12/20",
    id: 0,
  },
  {
    FirstName: "Jahid",
    Date: new Date("05 / 09 / 2015"),
    Examination: "Philosophie",
    Note: "8/20",
    id: 1,
  },
  {
    FirstName: "Valentin",
    Date: new Date("05 / 09 / 2015"),
    Examination: "Philosophie",
    Note: "4/20",
    id: 2,
  },
  {
    FirstName: "Milton",
    Date: new Date("05 / 09 / 2015"),
    Examination: "Philosophie",
    Note: "10/20",
    id: 3,
  },
  {
    FirstName: "Gonesh",
    Date: new Date("01 / 09 / 2015"),
    Examination: "Français",
    Note: "14/20",
    id: 4,
  },
  {
    FirstName: "Valérie",
    Date: new Date("07 / 09 / 2015"),
    Examination: "Mathématiques",
    Note: "19/20",
    id: 5,
  },
  {
    FirstName: "Valentin",
    Date: new Date("01 / 09 / 2015"),
    Examination: "Français",
    Note: "11/20",
    id: 6,
  },
  {
    FirstName: "Eric",
    Date: new Date("01 / 10 / 2015"),
    Examination: "Philosophie",
    Note: "8/20",
    id: 7,
  },
  {
    FirstName: "Valentin",
    Date: new Date("07 / 09 / 2015"),
    Examination: "Mathématiques",
    Note: "14/20",
    id: 8,
  },
  {
    FirstName: "Valérie",
    Date: new Date("01 / 10 / 2015"),
    Examination: "Philosophie",
    Note: "12/20",
    id: 9,
  },
  {
    FirstName: "Eric",
    Date: new Date("07 / 09 / 2015"),
    Examination: "Mathématiques",
    Note: "14/20 ",
    id: 10,
  },
  {
    FirstName: "Valentin",
    Date: new Date("01 / 10 / 2015"),
    Examination: "Philosophie",
    Note: "10/20",
    id: 11,
  },
];
